###############################################################################################
# Server Configuration
###############################################################################################

server:
  port: 7001

spring:
  profiles:
    active: dev
  application:
    name: webService

---

###############################################################################################
# Mongo DB Configuration
###############################################################################################

spring:
  data:
    mongodb:
      uri: mongodb://user:123@localhost:27017/exampleDB
      authentication-database: exampleDB

---

###############################################################################################
# Rabbit MQ Configuration
###############################################################################################

spring:
  rabbitmq:
    addresses: localhost:15672
    username: admin
    password: 123

---