###############################################################################################
# Server Configuration
###############################################################################################

server:
  port: 7002

spring:
  profiles:
    active: dev
  application:
    name: notificationService

---

###############################################################################################
# Rabbit MQ Configuration
###############################################################################################

spring:
  rabbitmq:
    addresses: localhost:5672
    username: admin
    password: 123
  cloud:
    stream:
      bindings:
        newNotificationChannel:
          destination: newNotificationExchange # mapping cloud stream channel to rabbitmq exchange
          group: notification-group # only 1 consumer will receive the message
---

###############################################################################################
# Spring Security Configuration
###############################################################################################


