###############################################################################################
# Server Configuration
###############################################################################################

server:
  port: 7002

spring:
  profiles:
    active: dev
  application:
    name: notificationService

---

###############################################################################################
# Rabbit MQ Configuration
###############################################################################################

spring:
  rabbitmq:
    addresses: localhost:15672
    username: admin
    password: 123

---

###############################################################################################
# Spring Security Configuration
###############################################################################################


