/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.6.1/userguide/multi_project_builds.html
 */

rootProject.name = "java-web-app"

// order does matters
include("app-backend:ms-notification-service")
include("app-backend:ms-web-service")
include("app-gateway:api-gateway-spring")
include("app-infra:config-server")
