###############################################################################################
# Server Configuration
###############################################################################################

server:
  port: 7001

###############################################################################################
# Mongo DB Configuration
###############################################################################################

spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://user:123@localhost:27017/exampleDB
      authentication-database: exampleDB
