###############################################################################################
# Server Configuration
###############################################################################################

server.port: 9090

spring:
  profiles.active: dev
  application.name: apigateway

---

###############################################################################################
# Gateway Configuration
###############################################################################################

spring.cloud.gateway.routes:
  - id: testApi
    uri: http://localhost:3001/
    predicates:
      - Method=GET
      - Path=/api/testapi/**                                    # matches if the request path is, for example, /api/testapi/fakeapi
    filters:
      - RewritePath=/api/testapi(?<segment>/?.*), $\{segment}   # /api/testapi/something --becomes--> /fakeapi
  - id: web-service
    uri: http://localhost:7001/
    predicates:
      - Method=GET,POST,PUT,DELETE
      - Path=/api/web/**
    filters:
      - RewritePath=/api/web(?<segment>/?.*), $\{segment}
  - id: notification-service
    uri: ws://localhost:7002/
    predicates:
      - Path=/websocket/**