###############################################################################################
# Server Configuration
###############################################################################################

server:
  port: 7002

###############################################################################################
# Spring Security Configuration
###############################################################################################
spring:
  security:
    user:
      name: user
      password: 1234
