###############################################################################################
# Server Configuration
###############################################################################################

server:
  port: 7002

###############################################################################################
# Spring Security Configuration
###############################################################################################


